---
- name: SETUP
  hosts: all #localhost
  gather_facts: false
  become_method: sudo

  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    default_user: '{{ lookup("env", "USER") }}'

  vars_prompt:
    - name: git_user
      prompt: git username
      private: false

    - name: git_email
      prompt: git email
      private: false

  tasks:
#    - import_tasks: tasks/apt_update.yml
#    - import_tasks: tasks/apt_install.yml
#    - import_tasks: tasks/pipx.yml
    - import_tasks: tasks/zsh.yml
#    - import_tasks: tasks/terminator.yml
#    - import_tasks: tasks/wireshark.yml
#    - import_tasks: tasks/git_repo.yml
#    - import_tasks: tasks/git_global.yml
