---
- name: OPSEC
  hosts: localhost
  become_method: sudo
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
    default_shell: '{{ lookup("env", "SHELL") }}'
  vars_prompt:
    - name: git_user
      prompt: git username
      private: false

    - name: git_email
      prompt: git email
      private: false

  tasks:
  - import_tasks: tasks/update.yml
  - import_tasks: tasks/apt.yml
  - import_tasks: tasks/pipx.yml
  - import_tasks: tasks/shell.yml
  - import_tasks: tasks/terminator.yml
#  - import_tasks: tasks/wireshark.yml
  - import_tasks: tasks/git.yml
