---
- name: OPSEC
  hosts: localhost
  become_method: sudo
  gather_facts: false
  vars:
    ansible_python_interpreter: "/usr/bin/python3"

  tasks:
  - name: Insert/Update configuration block in test.txt
    blockinfile:
      path: ./test.txt
      block: |
        Match User ansible-agent
