#!/usr/bin/env python3

import sys
from impacket.smbconnection import SMBConnection

if len(sys.argv) != 2:
	print("Give an IP address")
	exit()

RED_BOLD = '\033[1;31m'
RESET = '\033[0m'

ip = sys.argv[1]

myconnection = SMBConnection("duck",ip)
myconnection.login("", "")


print("NetBIOS domain name:\t",myconnection.getServerDomain())
print("DNS domain name:\t",myconnection.getServerDNSDomainName())

print()

print("NetBIOS computer name:\t",myconnection.getServerName())

dnsname = myconnection.getServerDNSHostName()
print("Full DNS name:\t\t",dnsname)
print("  Hostname:\t\t",dnsname.split('.',1)[0])
#print("Maybe?:\t\t",myconnection.getRemoteName())

myconnection.close()
