#!/usr/bin/env python3

import sys
from impacket.smbconnection import SMBConnection

if len(sys.argv) != 2:
	print("Give an IP address")
	exit()

RED_BOLD = '\033[1;31m'
RESET = '\033[0m'

ip = sys.argv[1]

myconnection = SMBConnection("duck", ip)
myconnection.login("", "")

domname = myconnection.getServerDNSDomainName()
print("NetBIOS domain name:\t{}".format(myconnection.getServerDomain()))
print("DNS domain name:\t{}\n".format(domname))

print("NetBIOS computer name:\t{}".format(myconnection.getServerName()))
print("Full DNS name:\t\t{}\n".format(myconnection.getServerDNSHostName()))

'''
tree_id = myconnection.connectTree("IPC$")
try:
	myconnection.openFile(tree_id,"srvsvc")
	print("Null auth:\t\t" + RED_BOLD + "YES" + RESET)
except:
	print("Null auth:\t\tno")

try:
	myconnection.login("guest", "")
	print("Guest account:\t\t" + RED_BOLD + "YES" + RESET)
except:
	print("Guest account:\t\tno")
'''
myconnection.close()

myconnection = SMBConnection("duck", ip)
myconnection.login("", "", domname)

tree_id = myconnection.connectTree("IPC$")
try:
	myconnection.openFile(tree_id, "srvsvc")
	print("Null auth:\t\t" + RED_BOLD + "YES" + RESET)
except:
	print("Null auth:\t\tno")

try:
	myconnection.login("guest", "", domname)
	print("Guest account:\t\t" + RED_BOLD + "YES" + RESET)
except:
	print("Guest account:\t\tno")

myconnection.close()
