- block:

  - name: "APT : install tools"
    apt:
      name: "{{ item.name }}"
      state: "{{ item.state }}"
    with_items:
      - { name: pipx, state: latest }
      - { name: terminator, state: latest }
      - { name: wireshark, state: latest }

  become: true
  rescue:
    - name: Errors
      ansible.builtin.debug:
        msg: 'ERROR'
