- block:
  - name: 'APT : install tools'
    apt:
      name: '{{ item.name }}'
    loop:
      - { name: zsh }
      - { name: terminator }
      - { name: wireshark }
      - { name: nmap }
      - { name: smbclient }

  become: true
