- block:

  - name: 'GIT : global settings'
    community.general.git_config:
      name: '{{ item.name }}'
      scope: '{{ item.scope }}'
      value: '{{ item.value }}'
    loop:
      - { name: user.name, scope: global, value: '{{ git_user }}' }
      - { name: user.email, scope: global, value: '{{ git_email }}' }
      - { name: pull.rebase, scope: global, value: true }

  - name: 'GIT : SSH keypair'
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_rsa
