- block:

  - name: 'GIT : repo submodules init'
    command: git submodule update --init
    changed_when: output.stdout is search("Submodule path")
    register: output

  - name: 'GIT : add global config'
    community.general.git_config:
      name: '{{ item.name }}'
      scope: '{{ item.scope }}'
      value: '{{ item.value }}'
    loop:
      - { name: user.name, scope: global, value: '{{ git_user }}' }
      - { name: user.email, scope: global, value: '{{ git_email }}' }
      - { name: pull.rebase, scope: global, value: 'true' }

  - name: 'GIT : create .ssh/ directory'
    file:
      path: ~/.ssh/
      state: directory
      mode: '700'

  - name: 'GIT : create ssh keypair'
    community.crypto.openssh_keypair:
      path: ~/.ssh/id_rsa
