# CONFIG FOR BASH
- block:

  - name: '.BASHRC : add config'
    blockinfile:
      path: ~/.bashrc
      block: '{{ lookup("file", "../shell/bashrc") }}'

  when: default_shell is search("/bash")


# CONFIG FOR ZSH
- block:

  - name: '.ZSHRC : change config'
    lineinfile:
      path: ~/.zshrc
      regexp: '{{ item.regexp }}'
      line: '{{ item.line }}'
      backrefs: yes
    loop:
      - { regexp: ^PROMPT_ALTERNATIVE=twoline$, line: PROMPT_ALTERNATIVE=oneline }
      - { regexp: ^NEWLINE_BEFORE_PROMPT=yes$, line: NEWLINE_BEFORE_PROMPT=no }

  - name: '.ZSHRC : add config'
    blockinfile:
      path: ~/.zshrc
      block: '{{ lookup("file", "../shell/zshrc") }}'

  when: default_shell is search("/zsh")
