# CONFIG FOR BASH
- block:
  - name: 'BASH : add .bashrc config'
    blockinfile:
      path: ~/.bashrc
      block: '{{ lookup("file", "../shell/bashrc") }}'

  when: default_shell is search('/bash')


# CONFIG FOR ZSH
- block:
  - name: 'ZSH : change .zshrc config'
    lineinfile:
      path: ~/.zshrc
      regexp: '{{ item.regexp }}'
      line: '{{ item.line }}'
      backrefs: true
    loop:
      - { regexp: ^PROMPT_ALTERNATIVE=twoline$, line: PROMPT_ALTERNATIVE=oneline }
      - { regexp: ^NEWLINE_BEFORE_PROMPT=yes$, line: NEWLINE_BEFORE_PROMPT=no }

  - name: 'ZSH : add .zshrc config'
    blockinfile:
      path: ~/.zshrc
      block: '{{ lookup("file", "../shell/zshrc") }}'

  when: default_shell is search('/zsh')
