- block:

  - name: 'WIRESHARK : add config'
    blockinfile:
      path: '{{ item.path }}'
      block: '{{ item.block }}'
      create: yes
    loop:
      - { path: ~/.config/wireshark/preferences, block: '{{ lookup("file", "../wireshark/preferences") }}' }
      - { path: ~/.config/wireshark/dfilter_buttons, block: '{{ lookup("file", "../wireshark/dfilter_buttons") }}' }
