- block:
  - name: 'ZSH : change default shell'
    user:
      name: '{{ ansible_env.USER }}'
      shell: /usr/bin/zsh
    become: true

  - name: 'ZSH : pull zsh plugins'
    git:
      repo: '{{ item.repo }}'
      dest: '{{ item.dest }}'
    loop:
      - { repo: http://github.com/zsh-users/zsh-autosuggestions, dest: "{{ ansible_env.HOME }}/.zsh/zsh-autosuggestions" }
      - { repo: https://github.com/zsh-users/zsh-syntax-highlighting, dest: "{{ ansible_env.HOME }}/.zsh/zsh-syntax-highlighting" }

  - name: 'ZSH : copy .zshrc'
    copy:
      src: ../zsh/.zshrc
      dest: "{{ ansible_env.HOME }}/.zshrc"
      mode: '644'
