- block:
  - name: 'ZSH : change default shell'
    user:
      name: '{{ default_user }}'
      shell: /usr/bin/zsh
    become: true

  - name: 'ZSH : pull zsh-autosuggestions folder'
    git:
      repo: http://github.com/zsh-users/zsh-autosuggestions
      dest: ~/.zsh/zsh-autosuggestions

  - name: 'ZSH : pull zsh-syntax-highlighting folder'
    git:
      repo: https://github.com/zsh-users/zsh-syntax-highlighting
      dest: ~/.zsh/zsh-syntax-highlighting

  - name: 'ZSH : copy .zshrc'
    copy:
      src: ../zsh/.zshrc
      dest: ~/.zshrc
      mode: '644'
