- block:
  - name: 'ZSH : change default shell'
    user:
      name: '{{ default_user }}'
      shell: /usr/bin/zsh
    become: true

  - name: 'ZSH : pull zsh plugins'
    git:
      repo: '{{ item.repo }}'
      dest: '{{ item.dest }}'
    loop:
      - { repo: http://github.com/zsh-users/zsh-autosuggestions, dest: ~/.zsh/zsh-autosuggestions }
      - { repo: https://github.com/zsh-users/zsh-syntax-highlighting, dest: ~/.zsh/zsh-syntax-highlighting }

  - name: 'ZSH : copy .zshrc'
    copy:
      src: ../zsh/.zshrc
      dest: ~/.zshrc
      mode: '644'
