- block:
  - name: 'ZSH : change default shell'
    user:
      name: '{{ default_user }}'
      shell: /usr/bin/zsh
    become: true

  - name: 'ZSH : add .zshrc'
    copy:
      src: ../zsh/.zshrc
      dest: ~/.zshrc
      mode: '644'

  - name: 'ZSH : add autosuggestions'
    git:
      repo: http://github.com/zsh-users/zsh-autosuggestions
      dest: ~/.zsh/zsh-autosuggestions

  # change shell
  # reboot
