- block:

  - name: ".ZSHRC : change settings"
    ansible.builtin.lineinfile:
      path: ~/.zshrc
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      backrefs: yes
    with_items:
      - { regexp: '^PROMPT_ALTERNATIVE=twoline$', line: 'PROMPT_ALTERNATIVE=oneline' }
      - { regexp: '^NEWLINE_BEFORE_PROMPT=yes$', line: 'NEWLINE_BEFORE_PROMPT=no' }

  - name: ".ZSHRC : add settings"
    blockinfile:
      path: ~/.zshrc
      block: "{{ lookup('file', '../shell/.zshrc') }}"

  rescue:
    - name: Errors
      ansible.builtin.debug:
        msg: 'ERROR'
